DROP DATABASE IF EXISTS mini_world_db;
CREATE DATABASE mini_world_db;
USE mini_world_db;

CREATE TABLE INTRUDERS (
    User_Id INT AUTO_INCREMENT PRIMARY KEY,
    Name VARCHAR(30) NOT NULL,
    Gender CHAR(1) NOT NULL CHECK (Gender IN ('M', 'F', 'O')),
    Height INT NOT NULL CHECK(Height between 1 and 300),
    Weight INT NOT NULL CHECK(Weight>0),
    Intelligence INT NOT NULL CHECK(Intellegince between 50 and 170),
    Time_Of_Entry TIME NOT NULL,
    Location_Id INT NOT NULL
);

CREATE TABLE MODERATORS (
    Moderator_Id INT AUTO_INCREMENT PRIMARY KEY,
    Name VARCHAR(30) NOT NULL -- Did not have this in the prev submissions for some reason
);

CREATE TABLE FOODIMALS_SPECIES(
    Species_Id INT AUTO_INCREMENT PRIMARY KEY,
    Species_Name VARCHAR(30) NOT NULL
);

CREATE TABLE INDIVIDUAL_FOODIMAL_CREATURES(
    Creature_Id INT AUTO_INCREMENT PRIMARY KEY,
    Species_Id INT, -- This can be null if this is populatory species [Referenced later]
    Location_Id INT NOT NULL,
    Populatory_Species_Id INT, -- This can be null if it is not a populatory species
    FOREIGN KEY (Species_Id) REFERENCES FOODIMALS_SPECIES(Species_Id) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE ISLAND_REGIONS(
    Region_Id INT AUTO_INCREMENT PRIMARY KEY,
    Region_Name VARCHAR(30) NOT NULL,
    Threat_To_Intruders INT NOT NULL
);

CREATE TABLE LIVECORP_COLONY(
    Colony_Id INT AUTO_INCREMENT PRIMARY KEY,
    Region_Id INT NOT NULL,
    FOREIGN KEY (Region_Id) REFERENCES ISLAND_REGIONS(Region_Id) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE POPULATORY_SPECIES(
    Species_Id INT PRIMARY KEY,
    Spawn_Per_Birth INT NOT NULL,
    FOREIGN KEY (Species_Id) REFERENCES FOODIMALS_SPECIES(Species_Id) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE INVENTIONS(
    Item_Owner INT,
    Item_Name VARCHAR(30),
    PRIMARY KEY (Item_Owner, Item_Name),
    FOREIGN KEY (Item_Owner) REFERENCES INTRUDERS(User_Id) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE LIVECORP_CELLS(
    Cell_Id INT NOT NULL AUTO_INCREMENT,
    Colony_Id INT NOT NULL,
    Type VARCHAR(30) NOT NULL CHECK (Type IN ('MANUFACTURING', 'RESEARCH', 'RECREATION', 'HOUSING')),
    PRIMARY KEY (Cell_Id, Colony_Id),
    FOREIGN KEY (Colony_Id) REFERENCES LIVECORP_COLONY(Colony_Id) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE WEAKNESS(
    Species_Id INT NOT NULL,
    Item_Inventor_Id INT NOT NULL,
    Item_Name VARCHAR(30) NOT NULL,
    FOREIGN KEY (Species_Id) REFERENCES FOODIMALS_SPECIES(Species_Id) ON UPDATE CASCADE ON DELETE CASCADE,
    FOREIGN KEY (Item_Inventor_Id, Item_Name) REFERENCES INVENTIONS(Item_Owner, Item_Name) ON UPDATE CASCADE ON DELETE CASCADE,
    PRIMARY KEY (Species_Id, Item_Inventor_Id, Item_Name)
);

CREATE TABLE SUSPIOUS_ACTIVITIES (
    Intruder_Id INT NOT NULL,
    Creature_Id INT NOT NULL,
    Colony_Id INT NOT NULL,
    Cell_Id INT NOT NULL,
    FOREIGN KEY (Intruder_Id) REFERENCES INTRUDERS(User_Id) ON UPDATE CASCADE ON DELETE CASCADE,
    FOREIGN KEY (Creature_Id) REFERENCES INDIVIDUAL_FOODIMAL_CREATURES(Creature_Id) ON UPDATE CASCADE ON DELETE CASCADE,
    FOREIGN KEY (Colony_Id) REFERENCES LIVECORP_COLONY(Colony_Id) ON UPDATE CASCADE ON DELETE CASCADE,
    FOREIGN KEY (Cell_Id) REFERENCES LIVECORP_CELLS(Cell_Id) ON UPDATE CASCADE ON DELETE CASCADE,
    PRIMARY KEY (Intruder_Id, Creature_Id, Colony_Id, Cell_Id)
);

CREATE TABLE COMBAT_EVENT(
    Intruder_Id INT NOT NULL,
    Creature_Id INT NOT NULL,
    Item_Owner_Id INT NOT NULL,
    Region_Id INT NOT NULL,
    Item_Name VARCHAR(30) NOT NULL,
    FOREIGN KEY (Intruder_Id) REFERENCES INTRUDERS(User_Id) ON UPDATE CASCADE ON DELETE CASCADE,
    FOREIGN KEY (Creature_Id) REFERENCES INDIVIDUAL_FOODIMAL_CREATURES(Creature_Id) ON UPDATE CASCADE ON DELETE CASCADE,
    FOREIGN KEY (Item_Owner_Id, Item_Name) REFERENCES INVENTIONS(Item_Owner, Item_Name) ON UPDATE CASCADE ON DELETE CASCADE,
    FOREIGN KEY (Region_Id) REFERENCES ISLAND_REGIONS(Region_Id) ON UPDATE CASCADE ON DELETE CASCADE,
    PRIMARY KEY (Intruder_Id, Creature_Id, Item_Owner_Id, Item_Name)
);

CREATE TABLE CREATES(
    Moderator_Id INT NOT NULL,
    Species_Id INT NOT NULL,
    Creature_Id INT,
    FOREIGN KEY (Creature_Id) REFERENCES INDIVIDUAL_FOODIMAL_CREATURES(Creature_Id) ON UPDATE CASCADE ON DELETE CASCADE,
    FOREIGN KEY (Moderator_Id) REFERENCES MODERATORS(Moderator_Id) ON UPDATE CASCADE ON DELETE CASCADE,
    FOREIGN KEY (Species_Id) REFERENCES FOODIMALS_SPECIES(Species_Id) ON UPDATE CASCADE ON DELETE CASCADE,
    PRIMARY KEY (Moderator_Id, Species_Id)
);

CREATE TABLE DESCRIPTIONS(
    Decription VARCHAR(255) NOT NULL, -- why get it confused with DESC in sql
    Item_Owner_Id INT NOT NULL,
    Item_Name VARCHAR(30) NOT NULL,
    FOREIGN KEY (Item_Owner_Id, Item_Name) REFERENCES INVENTIONS(Item_Owner, Item_Name) ON UPDATE CASCADE ON DELETE CASCADE,
    PRIMARY KEY (Item_Owner_Id, Item_Name, `Desc`)
);

CREATE TABLE INVENTOR(
    Name VARCHAR (30) NOT NULL,
    Item_Owner_Id INT NOT NULL,
    Item_Name VARCHAR(30) NOT NULL,
    FOREIGN KEY (Item_Owner_Id, Item_Name) REFERENCES INVENTIONS(Item_Owner, Item_Name) ON UPDATE CASCADE ON DELETE CASCADE,
    PRIMARY KEY (Item_Owner_Id, Item_Name, Name)
);

CREATE TABLE ANIMAL (
    Name VARCHAR(30) NOT NULL,
    Species_Id INT NOT NULL,
    FOREIGN KEY (Species_Id) REFERENCES FOODIMALS_SPECIES(Species_Id) ON UPDATE CASCADE ON DELETE CASCADE,
    PRIMARY KEY (Species_Id, Name)
);

CREATE TABLE FOOD_ITEM (
    Name VARCHAR(30) NOT NULL,
    Species_Id INT NOT NULL,
    FOREIGN KEY (Species_Id) REFERENCES FOODIMALS_SPECIES(Species_Id) ON UPDATE CASCADE ON DELETE CASCADE,
    PRIMARY KEY (Species_Id, Name)
);

ALTER TABLE INTRUDERS ADD FOREIGN KEY (Location_Id) REFERENCES ISLAND_REGIONS(Region_Id) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE INDIVIDUAL_FOODIMAL_CREATURES ADD FOREIGN KEY (Populatory_Species_Id) REFERENCES POPULATORY_SPECIES(Species_Id) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE INDIVIDUAL_FOODIMAL_CREATURES ADD FOREIGN KEY (Location_Id) REFERENCES ISLAND_REGIONS(Region_Id) ON UPDATE CASCADE ON DELETE CASCADE;

